=== diretto/JavaClientTaskPlugin/conf/org/diretto/api/client/external/task/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="api-version" type="xs:string" />
				<xs:element name="service-class" type="xs:string" />
				<xs:element name="cache">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cache-config-file" type="xs:string" />
							<xs:element name="cache-name" type="xs:string" />
							<xs:element name="cache-activated" type="xs:boolean" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== diretto/JavaClientTaskPlugin/conf/org/diretto/api/client/external/task/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

	<name>org.diretto.api.external.task</name>
	<api-version>v2</api-version>
	<service-class>org.diretto.api.client.external.task.TaskServiceImpl</service-class>

	<cache>
		<cache-config-file>org/diretto/api/client/external/task/ehcache.xml</cache-config-file>
		<cache-name>TaskCache</cache-name>
		<cache-activated>true</cache-activated>
	</cache>

</config>
